[ 2025-03-05 01:07:56,264 ] root - INFO - Making predictions
[ 2025-03-05 01:07:56,264 ] root - INFO - Loading object from artifact/data_transformation/preprocessor.pkl
[ 2025-03-05 01:07:56,839 ] root - INFO - Loading object from artifact/model_training/model.pkl.zip
[ 2025-03-05 01:07:57,315 ] root - INFO - Preprocessing input data
[ 2025-03-05 01:07:57,315 ] root - INFO - Loading schema from config/schema.yaml
[ 2025-03-05 01:07:57,318 ] root - INFO - Extracting schema columns
[ 2025-03-05 01:07:57,320 ] root - ERROR - Error preprocessing input data: Error occurred python script name [/Users/mirza/Desktop/mirza7865-USVisa-MLOps-ProductionGrade/us_visa/pipline/prediction_pipeline.py] line number [75] error message ["['case_id'] not found in axis"]
[ 2025-03-05 01:07:57,320 ] root - ERROR - Error making predictions: Error occurred python script name [/Users/mirza/Desktop/mirza7865-USVisa-MLOps-ProductionGrade/us_visa/pipline/prediction_pipeline.py] line number [100] error message [Error occurred python script name [/Users/mirza/Desktop/mirza7865-USVisa-MLOps-ProductionGrade/us_visa/pipline/prediction_pipeline.py] line number [75] error message ["['case_id'] not found in axis"]]
